# Generated by Django 5.1.1 on 2024-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_original_user_query",
            field=models.BooleanField(default=False),
        ),
    ]
