# Generated by Django 5.1.1 on 2024-10-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_message_is_original_user_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_out_of_context_message",
            field=models.BooleanField(default=False),
        ),
    ]
