# Generated by Django 5.1.1 on 2024-10-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningobject",
            name="completed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningobject",
            name="started_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
