# Generated by Django 5.1.1 on 2024-10-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_course", "0005_activitylog_aiinteraction_assignmentsubmission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activitylog",
            old_name="student",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="aiinteraction",
            old_name="student",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="assignmentsubmission",
            old_name="student",
            new_name="user",
        ),
    ]
