# Development Dockerfile for Django

# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app/server

# Install dependencies
COPY ./requirements.txt /app/server/
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files to the app directory
# COPY nginx /app/
# COPY voila /app/
# COPY server /app/
COPY . /app/server

# Set environment variables for development
ENV DJANGO_ENV=development

RUN pwd && ls -l

# Expose port 8000 to the outside world
EXPOSE 8000

# Start Django application with live reload
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
